[
  {
    date: "2021-08-16T03:35:35.000Z",
    description:
      "aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis",
    category: "Transportation Expenses",
    amount: 680.8,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-03-02T12:55:10.000Z",
    description:
      "sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit",
    category: "Miscellaneous Expenses",
    amount: 956.2,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-28T21:36:10.000Z",
    description:
      "nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam",
    category: "",
    amount: 336.35,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-23T03:42:00.000Z",
    description:
      "urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam",
    category: "Debt Payments",
    amount: 531.57,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-01-17T05:20:01.000Z",
    description:
      "potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi",
    category: "Transportation Expenses",
    amount: 842.38,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-07-31T12:00:07.000Z",
    description:
      "donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet",
    category: "Insurance",
    amount: 796.42,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-06-27T23:48:25.000Z",
    description:
      "donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio",
    category: "Transportation Expenses",
    amount: 796.53,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-01-31T20:42:28.000Z",
    description:
      "amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",
    category: "",
    amount: 536.77,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-18T05:08:41.000Z",
    description:
      "a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra",
    category: "Miscellaneous Expenses",
    amount: 375.58,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-07-22T21:04:13.000Z",
    description:
      "cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",
    category: "Personal Care and Health",
    amount: 873.45,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-16T03:40:21.000Z",
    description:
      "praesent lectus vestibulum quam sapien varius ut blandit non interdum",
    category: "",
    amount: 165.76,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-26T03:12:09.000Z",
    description:
      "vivamus in felis eu sapien cursus vestibulum proin eu mi nulla",
    category: "Food and Groceries",
    amount: 468.18,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-21T13:21:06.000Z",
    description:
      "nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper",
    category: "Miscellaneous Expenses",
    amount: 608.05,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-15T13:59:51.000Z",
    description:
      "duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam",
    category: "Education and Professional Development",
    amount: 646.29,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-03-06T18:51:05.000Z",
    description:
      "neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh",
    category: "Education and Professional Development",
    amount: 226.9,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-11T18:40:59.000Z",
    description:
      "orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi",
    category: "Food and Groceries",
    amount: 63.45,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-27T04:50:11.000Z",
    description:
      "nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum",
    category: "Housing Expenses",
    amount: 385.64,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-09-20T06:21:04.000Z",
    description:
      "tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum",
    category: "Personal Care and Health",
    amount: 21.53,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-07-10T17:35:22.000Z",
    description:
      "justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit",
    category: "Personal Care and Health",
    amount: 416.18,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-15T18:02:39.000Z",
    description:
      "et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum",
    category: "Housing Expenses",
    amount: 785.44,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-27T12:57:59.000Z",
    description:
      "penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum",
    category: "Transportation Expenses",
    amount: 55.56,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-30T10:40:35.000Z",
    description:
      "amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit",
    category: "",
    amount: 307.68,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-12-02T14:43:44.000Z",
    description:
      "in felis donec semper sapien a libero nam dui proin leo odio porttitor",
    category: "Food and Groceries",
    amount: 232.97,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-11-05T04:05:18.000Z",
    description:
      "sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",
    category: "",
    amount: 241.81,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-23T03:01:01.000Z",
    description:
      "sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat",
    category: "Utilities and Services",
    amount: 990.85,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-08-14T10:57:32.000Z",
    description:
      "duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus",
    category: "Transportation Expenses",
    amount: 372.84,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-08-19T01:39:31.000Z",
    description:
      "enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",
    category: "Entertainment and Recreation",
    amount: 671.27,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-08-05T20:11:06.000Z",
    description:
      "adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc",
    category: "Insurance",
    amount: 64.12,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-08-10T07:51:49.000Z",
    description:
      "in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis",
    category: "Insurance",
    amount: 986.35,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-02-27T20:59:47.000Z",
    description:
      "libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit",
    category: "Housing Expenses",
    amount: 298.61,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-10-26T22:32:24.000Z",
    description:
      "est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante",
    category: "Personal Care and Health",
    amount: 552.22,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-17T09:52:27.000Z",
    description:
      "tortor duis mattis egestas metus aenean fermentum donec ut mauris",
    category: "Utilities and Services",
    amount: 719.29,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-14T23:23:51.000Z",
    description:
      "est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante",
    category: "Entertainment and Recreation",
    amount: 336.43,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-10T23:29:22.000Z",
    description:
      "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque",
    category: "Debt Payments",
    amount: 337.38,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-02-17T16:05:24.000Z",
    description:
      "luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis",
    category: "",
    amount: 860.71,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-06-07T17:16:30.000Z",
    description:
      "lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer",
    category: "Transportation Expenses",
    amount: 823.3,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-05-10T23:14:43.000Z",
    description:
      "in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum",
    category: "Utilities and Services",
    amount: 371.51,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-05-15T20:16:13.000Z",
    description:
      "suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",
    category: "Utilities and Services",
    amount: 569.56,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-05-18T00:13:24.000Z",
    description:
      "sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras",
    category: "",
    amount: 799.72,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-25T00:05:03.000Z",
    description:
      "adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",
    category: "",
    amount: 420.91,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-08T11:02:02.000Z",
    description:
      "eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero",
    category: "",
    amount: 998.74,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-10-26T05:39:24.000Z",
    description:
      "est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus",
    category: "Entertainment and Recreation",
    amount: 319.98,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-06T13:26:42.000Z",
    description:
      "massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi",
    category: "Housing Expenses",
    amount: 458.96,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-01-09T16:05:41.000Z",
    description:
      "sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor",
    category: "Insurance",
    amount: 138.53,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-01T18:03:19.000Z",
    description:
      "sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",
    category: "Housing Expenses",
    amount: 210.94,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-10-30T18:18:43.000Z",
    description:
      "quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum",
    category: "Transportation Expenses",
    amount: 941.29,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-08-15T04:03:31.000Z",
    description:
      "libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti",
    category: "",
    amount: 157.24,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-06-18T04:44:20.000Z",
    description:
      "sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus",
    category: "Personal Care and Health",
    amount: 233.02,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-22T09:57:27.000Z",
    description:
      "lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero",
    category: "Miscellaneous Expenses",
    amount: 797.11,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-06-12T19:57:50.000Z",
    description: "porttitor pede justo eu massa donec dapibus duis at velit",
    category: "Utilities and Services",
    amount: 768.35,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-02T01:47:57.000Z",
    description:
      "volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper",
    category: "Transportation Expenses",
    amount: 91.23,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-11-26T03:34:33.000Z",
    description:
      "porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris",
    category: "",
    amount: 612.21,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-07-19T14:30:09.000Z",
    description:
      "volutpat in congue etiam justo etiam pretium iaculis justo in hac",
    category: "Education and Professional Development",
    amount: 567.0,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-07-12T20:24:17.000Z",
    description:
      "nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices",
    category: "Transportation Expenses",
    amount: 883.58,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-08-08T16:25:34.000Z",
    description:
      "ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien",
    category: "Food and Groceries",
    amount: 606.3,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-20T05:38:02.000Z",
    description:
      "quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",
    category: "Food and Groceries",
    amount: 125.91,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-05-08T22:57:42.000Z",
    description:
      "amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus",
    category: "Personal Care and Health",
    amount: 673.79,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-02-05T21:18:38.000Z",
    description:
      "vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci",
    category: "Insurance",
    amount: 772.34,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-01-02T08:21:11.000Z",
    description:
      "ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus",
    category: "Transportation Expenses",
    amount: 629.28,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-06-17T13:19:36.000Z",
    description:
      "interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue",
    category: "Food and Groceries",
    amount: 301.82,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-09-13T01:05:43.000Z",
    description:
      "ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit",
    category: "Miscellaneous Expenses",
    amount: 26.26,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-08-29T18:49:48.000Z",
    description:
      "neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit",
    category: "Insurance",
    amount: 449.46,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-02-09T23:53:16.000Z",
    description:
      "nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue",
    category: "Transportation Expenses",
    amount: 691.78,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-05-25T06:49:02.000Z",
    description:
      "ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh",
    category: "Education and Professional Development",
    amount: 318.47,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-06-19T18:37:07.000Z",
    description:
      "pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper",
    category: "Utilities and Services",
    amount: 520.3,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-26T06:46:19.000Z",
    description:
      "nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero",
    category: "Utilities and Services",
    amount: 673.66,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-27T20:17:23.000Z",
    description:
      "ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis",
    category: "",
    amount: 82.9,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-18T05:09:50.000Z",
    description:
      "elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    category: "Utilities and Services",
    amount: 430.1,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-04-07T06:45:42.000Z",
    description:
      "quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",
    category: "Utilities and Services",
    amount: 328.15,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-10-24T22:25:23.000Z",
    description:
      "sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui",
    category: "Utilities and Services",
    amount: 259.9,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-12T00:08:28.000Z",
    description:
      "nullam varius nulla facilisi cras non velit nec nisi vulputate",
    category: "Education and Professional Development",
    amount: 979.95,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-04-22T08:13:42.000Z",
    description:
      "dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer",
    category: "Insurance",
    amount: 159.06,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-08-20T02:08:11.000Z",
    description: "sit amet erat nulla tempus vivamus in felis eu sapien",
    category: "",
    amount: 522.71,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-01-02T09:13:32.000Z",
    description:
      "amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor",
    category: "Utilities and Services",
    amount: 614.67,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-06-25T07:52:01.000Z",
    description:
      "quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at",
    category: "Entertainment and Recreation",
    amount: 325.56,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-11T08:09:37.000Z",
    description:
      "id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet",
    category: "Debt Payments",
    amount: 565.01,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-03-01T09:01:12.000Z",
    description:
      "ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna",
    category: "Food and Groceries",
    amount: 382.62,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-07-04T15:00:32.000Z",
    description: "non mi integer ac neque duis bibendum morbi non quam",
    category: "",
    amount: 571.92,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-10-02T17:55:42.000Z",
    description:
      "posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum",
    category: "Debt Payments",
    amount: 41.3,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-06T09:23:12.000Z",
    description:
      "duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac",
    category: "Education and Professional Development",
    amount: 80.95,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-17T03:08:08.000Z",
    description:
      "nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros",
    category: "Utilities and Services",
    amount: 797.69,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-14T11:58:16.000Z",
    description:
      "porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique",
    category: "Transportation Expenses",
    amount: 921.29,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-09-21T22:22:48.000Z",
    description: "potenti in eleifend quam a odio in hac habitasse platea",
    category: "Insurance",
    amount: 530.33,
    paymentMethod: "Mobile Payment",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-08-16T15:38:23.000Z",
    description:
      "at turpis a pede posuere nonummy integer non velit donec diam",
    category: "Utilities and Services",
    amount: 809.39,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-08-10T15:13:53.000Z",
    description:
      "id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae",
    category: "Personal Care and Health",
    amount: 247.76,
    paymentMethod: "Credit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-06-18T23:54:13.000Z",
    description:
      "volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis",
    category: "Entertainment and Recreation",
    amount: 646.21,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-04-21T17:50:46.000Z",
    description:
      "justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque",
    category: "Education and Professional Development",
    amount: 828.82,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-01-29T17:23:34.000Z",
    description:
      "ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet",
    category: "",
    amount: 393.05,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-11-01T03:16:43.000Z",
    description: "rutrum neque aenean auctor gravida sem praesent id massa id",
    category: "Food and Groceries",
    amount: 237.73,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-08T20:41:29.000Z",
    description:
      "consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio",
    category: "Miscellaneous Expenses",
    amount: 405.66,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-12-10T09:03:20.000Z",
    description:
      "nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam",
    category: "Housing Expenses",
    amount: 744.26,
    paymentMethod: "Cash",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-02-26T06:48:34.000Z",
    description:
      "adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at",
    category: "Transportation Expenses",
    amount: 132.18,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-05-18T17:04:57.000Z",
    description:
      "penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean",
    category: "Miscellaneous Expenses",
    amount: 283.81,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-05-07T04:45:34.000Z",
    description:
      "etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut",
    category: "Transportation Expenses",
    amount: 8.92,
    paymentMethod: "Mobile Payment",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-05T20:01:06.000Z",
    description:
      "a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet",
    category: "Personal Care and Health",
    amount: 858.28,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-06-25T14:54:01.000Z",
    description:
      "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum",
    category: "Food and Groceries",
    amount: 942.29,
    paymentMethod: "Credit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-04-10T22:12:14.000Z",
    description:
      "mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus",
    category: "Transportation Expenses",
    amount: 989.8,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-04-03T12:31:12.000Z",
    description:
      "pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa",
    category: "Personal Care and Health",
    amount: 641.84,
    paymentMethod: "Debit Card",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2020-01-14T07:41:30.000Z",
    description:
      "pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget",
    category: "Insurance",
    amount: 811.47,
    paymentMethod: "Cash",
    receipt: false,
    userEmail: "test@gmail.com",
  },
  {
    date: "2021-09-12T22:27:02.000Z",
    description:
      "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula",
    category: "Food and Groceries",
    amount: 237.92,
    paymentMethod: "Debit Card",
    receipt: true,
    userEmail: "test@gmail.com",
  },
];
